Cherry-pick r271586. rdar://problem/73477459
    [AppleWin 32bit] LLInt C Loop: LowLevelInterpreter.cpp(90,7): error C2653: 'WebConfig': is not a class or namespace name
    https://bugs.webkit.org/show_bug.cgi?id=220405

    Reviewed by Fujii Hironori.

    Add a missing #if ENABLE(UNIFIED_AND_FREEZABLE_CONFIG_RECORD).

    * llint/LowLevelInterpreter.cpp:

    Canonical link: https://commits.webkit.org/233122@trunk
    git-svn-id: https://svn.webkit.org/repository/webkit/trunk@271586 268f45cc-cd09-0410-ab3c-d52691b4dbfc

Canonical link: https://commits.webkit.org/232923.50@safari-611-branch
git-svn-id: https://svn.webkit.org/repository/webkit/branches/safari-611-branch@271852 268f45cc-cd09-0410-ab3c-d52691b4dbfc